//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: System.Reflection.AssemblyTitle("FFImageLoading.ImageSourceHandler")]
[assembly: System.Reflection.AssemblyCompany("Sharpnado")]
[assembly: System.Reflection.AssemblyDescription("Caching-enabled ImageSourceHandler for iOS and Xamarin.Forms")]
[assembly: System.Reflection.AssemblyProduct("FFImageLoading.ImageSourceHandler")]
[assembly: System.Reflection.AssemblyCopyright("Copyright © Sharpnado 2019")]
[assembly: System.Reflection.AssemblyVersion("1.0.0")]
[assembly: System.Reflection.AssemblyFileVersion("1.0.0")]


